# Generated by Django 3.2.16 on 2024-03-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=256)),
                ('short_ru', models.CharField(max_length=12)),
                ('eng', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GeoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=256)),
                ('name_eng', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TerritorialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=256)),
                ('name_eng', models.CharField(max_length=256)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='homepage.districtname')),
                ('geo_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_category', to='homepage.geocategory')),
            ],
        ),
    ]
