# Generated by Django 3.2.16 on 2024-03-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contingents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('age', models.CharField(max_length=256, verbose_name='Возраст')),
                ('sex', models.CharField(max_length=256, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Контингент',
                'verbose_name_plural': 'Контингенты',
            },
        ),
        migrations.CreateModel(
            name='DistrictName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('short_ru', models.CharField(max_length=12)),
                ('title_eng', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
            },
        ),
        migrations.CreateModel(
            name='GeoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title_eng', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Тип территории',
                'verbose_name_plural': 'Типы территорий',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Период отчета',
                'verbose_name_plural': 'Период отчета',
            },
        ),
        migrations.CreateModel(
            name='ResidencePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title_eng', models.CharField(blank=True, max_length=256, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('num_form', models.CharField(max_length=10, unique=True, verbose_name='Номер формы')),
                ('count_table', models.PositiveSmallIntegerField(null=True, verbose_name='Кол-во таблиц')),
            ],
            options={
                'verbose_name': 'Отчетная форма',
                'verbose_name_plural': 'Отчетные формы',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='TerritorialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title_eng', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='homepage.districtname', verbose_name='Округ')),
                ('geo_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_category', to='homepage.geocategory', verbose_name='Тип территории')),
            ],
            options={
                'verbose_name': 'Территориальная единица',
                'verbose_name_plural': 'Территориальные единицы',
            },
        ),
        migrations.CreateModel(
            name='TableForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('table_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Номер таблицы')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.statform', verbose_name='Номер формы')),
            ],
            options={
                'verbose_name': 'Таблицы форм',
                'verbose_name_plural': 'Таблицы форм',
                'unique_together': {('table_number', 'form')},
            },
        ),
        migrations.CreateModel(
            name='NameOfDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('short_name', models.CharField(max_length=128, verbose_name='Сокр. название')),
                ('first_name', models.BooleanField(verbose_name='Форма №1')),
                ('second_name', models.BooleanField(verbose_name='Форма №2')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.tableform', verbose_name='Название таблицы')),
            ],
            options={
                'verbose_name': 'Название нозологии',
                'verbose_name_plural': 'Список нозологий',
            },
        ),
    ]
