# Generated by Django 3.2.16 on 2024-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocategory',
            name='name_eng',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
