# Generated by Django 3.2.16 on 2024-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_geocategory_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocategory',
            name='name_eng',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
