# Generated by Django 3.2.16 on 2024-03-13 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20240313_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingents',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(122)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='contingents',
            name='sex',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Пол'),
        ),
    ]
