# Generated by Django 3.2.16 on 2024-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20240313_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.RenameModel(
            old_name='Period',
            new_name='PeriodMonth',
        ),
        migrations.AlterModelOptions(
            name='periodmonth',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцы'},
        ),
    ]
