# Generated by Django 3.2.16 on 2024-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_geocategory_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtname',
            name='eng',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='name_eng',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
