# Generated by Django 3.2.16 on 2024-03-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20240311_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtname',
            options={'verbose_name': 'Округ', 'verbose_name_plural': 'Округа'},
        ),
        migrations.AlterModelOptions(
            name='geocategory',
            options={'verbose_name': 'Тип территории', 'verbose_name_plural': 'Типы территорий'},
        ),
        migrations.AlterModelOptions(
            name='territorialunit',
            options={'verbose_name': 'Территориальная единица', 'verbose_name_plural': 'Территориальные единицы'},
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='homepage.districtname', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='geo_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_category', to='homepage.geocategory', verbose_name='Тип территории'),
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='name_eng',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='name_ru',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
