# Generated by Django 3.2.16 on 2024-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20240312_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtname',
            old_name='ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='geocategory',
            old_name='name_eng',
            new_name='title_eng',
        ),
        migrations.RenameField(
            model_name='geocategory',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='territorialunit',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='districtname',
            name='eng',
        ),
        migrations.RemoveField(
            model_name='territorialunit',
            name='name_eng',
        ),
        migrations.AddField(
            model_name='districtname',
            name='title_eng',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='territorialunit',
            name='title_eng',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
