# Generated by Django 3.2.16 on 2024-03-13 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smp',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='СМП'),
        ),
    ]
