# Generated by Django 3.2.16 on 2024-03-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20240313_1831'),
        ('first_form', '0003_auto_20240313_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstform',
            name='period_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.periodmonth', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='firstform',
            name='period_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.periodyear', verbose_name='Год'),
        ),
    ]
